Models/CollectiblePart.cs
using Orchard.ContentManagement;

namespace Proligence.Collections.Models {
    public class CollectiblePart : ContentPart {
    }
}

Models/CollectionPart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Orchard.ContentManagement;
using Orchard.ContentManagement.Utilities;
using Orchard.UI;
using Proligence.Collections.Services;
using Proligence.Collections.Settings;

namespace Proligence.Collections.Models {
    /// <summary>
    /// Describes a Collection, which can contain multiple items inside (as an n-m relation).
    /// This part implements IList interface, so the underlying collection can be operated on without direct use of ICollectionService.
    /// </summary>
    public class CollectionPart : ContentPart<CollectionPartRecord>, ICollectionAspect {
        private readonly LazyField<IList<Tuple<CollectionRelationRecord, IContent>>> _items = new LazyField<IList<Tuple<CollectionRelationRecord, IContent>>>();

        public ICollectionService CollectionService { get; set; }

        public LazyField<IList<Tuple<CollectionRelationRecord, IContent>>> ItemsField {
            get { return _items; }
        }

        /// <summary>
        /// All collection items with corresponding relation record
        /// </summary>
        public IList<Tuple<CollectionRelationRecord, IContent>> AllItems {
            get { return _items.Value; }
            set { _items.Value = value; }
        }

        public IEnumerable<IContent> AvailableItems { get; set; }

        /// <summary>
        /// Forces reloading of items held by this CollectionPart. 
        /// Should be called after performing CRUD list operations on this CollectionPart.
        /// </summary>
        public void ForceRefresh()
        {
            // forces call to setter to refresh items.
            ItemsField.Value = null;
        }

        public bool AllowAdding {
            get {
                var set = Settings.GetModel<CollectionSettings>();
                return set.AllowAdding;
            }
        }

        public bool AllowRemoving {
            get {
                var set = Settings.GetModel<CollectionSettings>();
                return set.AllowRemoving;
            }
        }

        public IEnumerable<IContent> Items
        {
            get
            {
                if (AllItems == null)
                {
                    return Enumerable.Empty<IContent>();
                }

                return AllItems
                    .OrderBy(t => t.Item1.Position, new FlatPositionComparer())
                    .Select(t => t.Item2);
            }
        }
    }
}

Models/CollectionPartRecord.cs
using System.Collections.Generic;
using Orchard.ContentManagement.Records;
using Orchard.Data.Conventions;

namespace Proligence.Collections.Models {
	
    public class CollectionPartRecord : ContentPartRecord {
        public CollectionPartRecord() {
             Items = new List<CollectionRelationRecord>(); 
        }

        [CascadeAllDeleteOrphan]
        public virtual IList<CollectionRelationRecord> Items { get; set; }
    }
}

Models/CollectionRelationRecord.cs
using Orchard.ContentManagement.Records;

namespace Proligence.Collections.Models
{
    /// <summary>
    /// n-m relation record (switch table) between Collections and products.
    /// </summary>
    public class CollectionRelationRecord
    {
            public virtual int Id { get; set; }
            public virtual CollectionPartRecord CollectionPartRecord { get; set; }
            public virtual ContentItemRecord ContentItemRecord { get; set; }
            public virtual string Position { get; set; }
    }
}

Models/ICollectionAspect.cs
using System.Collections.Generic;
using Orchard.ContentManagement;

namespace Proligence.Collections.Models
{
    /// <summary>
    /// Describes an item that contains other items.
    /// </summary>
    public interface ICollectionAspect : IContent
    {
        /// <summary>
        /// List of contained items.
        /// </summary>
        IEnumerable<IContent> Items { get; }
    }
}

Controllers/AdminController.cs
using System;
using System.Web.Mvc;
using Orchard;
using Orchard.Localization;
using Orchard.Mvc;
using Orchard.Mvc.Extensions;
using Orchard.Security;
using Orchard.UI.Admin;
using Orchard.UI.Notify;
using Proligence.Collections.Services;

namespace Proligence.Collections.Controllers
{
    [Admin, ValidateInput(false)]
    public class AdminController : Controller
    {
        private readonly IAuthorizer _authorizer;
        private readonly INotifier _notifier;
        private readonly ICollectionService _collectionService;
        private readonly IOrchardServices _services;

        public AdminController(IOrchardServices services, IAuthorizer authorizer, INotifier notifier, ICollectionService collectionService)
        {
            _authorizer = authorizer;
            _notifier = notifier;
            _collectionService = collectionService;
            _services = services;
            T = NullLocalizer.Instance;
        }

        public Localizer T { get; set; }

        [HttpPost]
        public ActionResult Add(int collectionId, int itemId, string returnUrl)
        {
            if (!_authorizer.Authorize(StandardPermissions.SiteOwner)) return new HttpUnauthorizedResult();
            var item = _services.ContentManager.Get(itemId);

            try
            {
                _collectionService.AddItem(item, collectionId);
                _notifier.Information(T("Item added to the collection successfully."));
            }
            catch (Exception ex)
            {
                _notifier.Error(T("Could not add item to the collection. Reason: {0}", ex.Message));
            }
            return this.RedirectLocal(returnUrl);
        }

        [HttpPost]
        public ActionResult Remove(int recordId, string returnUrl)
        {
            if (!_authorizer.Authorize(StandardPermissions.SiteOwner)) return new HttpUnauthorizedResult();

            try
            {
                _collectionService.RemoveItem(recordId);
                _notifier.Information(T("Item removed from the collection successfully."));
            }
            catch (Exception ex)
            {
                _notifier.Error(T("Could not remove item from the collection. Reason: {0}", ex.Message));
            }

            return this.RedirectLocal(returnUrl);
        }

        [HttpPost]
        public ActionResult MoveUp(int recordId, string returnUrl)
        {
            if (!_authorizer.Authorize(StandardPermissions.SiteOwner)) return new HttpUnauthorizedResult();
            if (!_collectionService.MoveUp(recordId)) _notifier.Information(T("Cannot move item up."));
            return this.RedirectLocal(returnUrl);

        }

        [HttpPost]
        public ActionResult MoveDown(int recordId, string returnUrl)
        {
            if (!_authorizer.Authorize(StandardPermissions.SiteOwner)) return new HttpUnauthorizedResult();
            if (!_collectionService.MoveDown(recordId)) _notifier.Information(T("Cannot move item down."));
            return this.RedirectLocal(returnUrl);

        }
    }
}

Views/DefinitionTemplates/CollectionSettings.cshtml
@model Proligence.Collections.Settings.CollectionSettings
    <fieldset>
    <div>
        @Html.LabelFor(m => m.OfPart, @T("Contains items with part"))
        @Html.DropDownListFor(m => m.OfPart, Model.AvailableParts)
        @Html.ValidationMessageFor(m => m.OfPart, "*")
        <span class="hint">@T("Choose a Collectible part to allow adding all available types.")</span>
    </div>
    <div>
        @Html.LabelFor(m => m.OfType, @T("Contains items of type"))
        @Html.DropDownListFor(m => m.OfType, Model.AvailableTypes)
        @Html.ValidationMessageFor(m => m.OfType, "*")
        <span class="hint">@T("Type must have a Collectible part attached in order to show here.")</span>
    </div>
        <div>
        @Html.CheckBoxFor(m => m.AllowAdding)
        <label class="forcheckbox" for="@Html.FieldIdFor(m => m.AllowAdding)">@T("Allow adding items to the collection?")</label>
        @Html.ValidationMessageFor(m => m.AllowAdding, "*")
    </div>
        <div>
        @Html.CheckBoxFor(m => m.AllowRemoving)
        <label class="forcheckbox" for="@Html.FieldIdFor(m => m.AllowRemoving)">@T("Allow removing items from the collection?")</label>
        @Html.ValidationMessageFor(m => m.AllowRemoving, "*")
    </div>
    </fieldset>

Views/EditorTemplates/Parts/Common.Collectible.cshtml
@model Proligence.Collections.Models.CollectiblePart

Views/EditorTemplates/Parts/Common.Collection.cshtml
@using Orchard.ContentManagement
@using Orchard.ContentManagement.Aspects
@using Proligence.Collections.Models
@using Proligence.Collections.Settings
@model Proligence.Collections.Models.CollectionPart
@{
    Style.Require("WidgetsAdmin");
    var returnUrl = Request.RawUrl;
    int count = Model.Items == null ? 0 : Model.Items.Count();
    int countAv = Model.AvailableItems == null ? 0 : Model.AvailableItems.Count();
    MvcHtmlString classAttr = null;
    if (count == 0)
    {
        classAttr = new MvcHtmlString(" class=\"widgets-none\"");
    }

    MvcHtmlString classAttrAv = null;
    if (countAv == 0)
    {
        classAttrAv = new MvcHtmlString(" class=\"widgets-none\"");
    }

    var settings = Model.Settings.GetModel<CollectionSettings>();
}
@if (Model.Items == null)
{
    <fieldset>
        <legend>@T("Collection settings")</legend>
        <div>
            <i>@T("<b>This item is a collection</b>. It means that you can add existing content items to it.")</i></div>
        <div>
            <i>@T("You will be able to add items to this collection after creating it, in \"Edit\" screen.")</i></div>
    </fieldset>
}
else
{
    <div id="widgets-placement">
        <div id="widgets-layers" class="widgets-container detail-view switchable">
            <div id="widgets-zones" class="widgets-listed">
                <ol>
                    <li@(classAttr)>
                        <h2>@T("Collection Items")</h2>
                        <ul class="widgets-zone-widgets">
                            @if (count > 0)
                            {
                                int i = 0;
                                foreach (var item in Model.AllItems)
                                {
                                <li class="widgets-this-layer">
                                        <h3>@Html.ItemAdminLink(T(item.Item2.As<ITitleAspect>().Title).Text, item.Item2.ContentItem)</h3>
                                        <div class="widgets-actions">
                                            @if (settings.AllowRemoving)
                                            {
                                                @Html.Link(T("Remove").Text, Url.Action("Remove", "Admin", new { Area = "Proligence.Collections", recordId = item.Item1.Id, returnUrl }), new { @class = "link", itemprop = "UnsafeUrl" })
                                            }
                                        </div>
                                        <div class="widgets-move-somewhere">
                                            <a href="@Url.Action("MoveUp", "Admin", new { Area = "Proligence.Collections", returnUrl, recordId = item.Item1.Id })" @(new MvcHtmlString(i == 0 ? "disabled='disabled'" : "")) class="widgets-move widgets-move-up" itemprop="UnsafeUrl">@T("Move up")</a>
                                            <a href="@Url.Action("MoveDown", "Admin", new { Area = "Proligence.Collections", returnUrl, recordId = item.Item1.Id })" @(new MvcHtmlString(++i == count ? "disabled='disabled'" : "")) class="widgets-move widgets-move-down" itemprop="UnsafeUrl">@T("Move down")</a>
                                        </div>
                                </li>
                                }
                            }
                        </ul>
                    </li>
                    @if (settings.AllowAdding)
                    {
                        <li@(classAttrAv)>
                            <h2>@T("Available Items")</h2>
                            <ul class="widgets-zone-widgets">
                                @if (countAv > 0)
                                {
                                    foreach (var item in Model.AvailableItems)
                                    {
                                    <li class="widgets-other-layer">
                                        @using (Html.BeginFormAntiForgeryPost())
                                        {
                                            <h3>@Html.ItemAdminLink(T(item.As<ITitleAspect>().Title).Text, item.ContentItem)</h3>
                                            <div class="widgets-actions">
                                                @if (settings.AllowAdding)
                                                {
                                                    @Html.Link(
                                                        T("Add to collection").Text, 
                                                        Url.Action(
                                                            "Add", 
                                                            "Admin", 
                                                            new { Area = "Proligence.Collections", itemId = item.Id, collectionId = Model.ContentItem.Id, returnUrl }), 
                                                        new { @class = "link", itemprop = "UnsafeUrl" })
                                                }
                                            </div>
                                            <div class="widgets-move-somewhere">
                                            </div>
                                        }
                                    </li>
                                    }
                                }
                            </ul>
                        </li>
                    
                    }
                </ol>
            </div>
        </div>
    </div>
}